In [58]:
# example of extending the Process class and adding shared attributes
from time import sleep
from multiprocessing import Process
from multiprocessing import Value
from multiprocessing import Array
from multiprocessing import Event
from multiprocessing import RawArray
from PIL import Image, ImageTk, ImageFont, ImageDraw, ImageChops
from matplotlib import pyplot as plt
import numpy as np

In [32]:
# custom process class
class CustomProcess(Process):
#     override the constructor
    def __init__(self, event, sharr):
        # execute the base constructor
        Process.__init__(self)
        # initialize integer attribute
        self.event = event
        self.sharr = sharr
        self.data = Value('i', 0)

    # override the run function
    def run(self):
        while(True):
            sleep(1)    
            # store the data variable
            self.data.value = int(100*np.random.random())
            np_arr = (np.random.random(6)*100).astype(np.uint8).reshape(2, 3)
            self.sharr = numpy_to_raw(np_arr)
            
            if self.event.is_set():
                break

In [33]:
def raw_to_numpy(raw, shape = (600, 800, 3)):
    return np.frombuffer(raw, dtype=np.uint8).reshape(shape)


def numpy_to_raw(np_arr):
    return RawArray(np.ctypeslib.as_ctypes_type(np_arr.dtype), np_arr.flatten())

In [34]:
event = Event()
sharr = RawArray('c', (1, 2, 3, 4, 5, 6))
process = CustomProcess(event, sharr)

# start the process
process.start()
# wait for the process to finish
print('Waiting for the child process to finish')

for i in range(0, 10):
    arr = raw_to_numpy(sharr, shape = (2, 3))
    print(arr)
    
#     data = [item for item in sharr]
#     print(data)
    sleep(0.1)

event.set()

# process.join()
# report the process attribute
print(f'Parent got: {process.data.value}')

Waiting for the child process to finish
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
Parent got: 0


In [27]:
np_arr = np.arange(6).astype(np.uint8).reshape(2, 3)
np_arr

array([[0, 1, 2],
       [3, 4, 5]], dtype=uint8)

In [39]:
np_arr = (np.random.random(6)*100).astype(np.uint8).reshape(2, 3)

In [52]:
sharr = RawArray('c', (1, 2, 3, 4, 5, 6))
for i in range(0, np_arr.flatten().shape[0]):
    print(np_arr.flatten()[i], type(np_arr.flatten()[i]))
    sharr[i] = int(np_arr.flatten()[i])

17 <class 'numpy.uint8'>
35 <class 'numpy.uint8'>
67 <class 'numpy.uint8'>
44 <class 'numpy.uint8'>
83 <class 'numpy.uint8'>
72 <class 'numpy.uint8'>


In [46]:
np_arr.flatten().shape

(6,)

In [59]:
def generate_random_image():
    fontpath = 'OpenSans-Regular.ttf'
    font11 = ImageFont.truetype(fontpath, 34)

    frame = np.zeros((448, 800, 3), np.uint8)

    words = 'Jamnik – jedna z ras psów pochodząca z Niemiec. Niemiecka nazwa jamnika Dachshund oznacza w dosłownym tłumaczeniu "borsuczy pies", etymologia nazwy związana jest z jego zbliżoną do borsuków budową oraz wykorzystywaniem tej rasy do polowania na zwierzęta ryjące nory.'.split(' ')
    # words = ['jamnik', 'chirality', 'nanoparticles', 'gold', 'liquid crystal', 'camera error', 'impact factor',
            # 'laser', 'samples', 'work', 'nematic', 'helical', 'danger', 'run', 'thorlabs', 'microscope', 'science',
            # 'strange', 'temperature']
    
    img_pil = Image.fromarray(frame)
    draw = ImageDraw.Draw(img_pil)
    for i in range(0, 40):
        clr = int(60 + 195*np.random.random())
        draw.text((int(700*np.random.random()), int(400*np.random.random())), np.random.choice(words), font = font11, fill = (clr, clr, clr))
    return np.array(img_pil)

In [60]:
img = generate_random_image()

In [63]:
type(img)

numpy.ndarray

In [64]:
img.shape

(448, 800, 3)

In [66]:
sharr = RawArray('c', img.shape[0]*img.shape[1]*img.shape[2])
for i in range(0, np_arr.flatten().shape[0]):
    print(np_arr.flatten()[i], type(np_arr.flatten()[i]))
    sharr[i] = int(np_arr.flatten()[i])

17 <class 'numpy.uint8'>
35 <class 'numpy.uint8'>
67 <class 'numpy.uint8'>
44 <class 'numpy.uint8'>
83 <class 'numpy.uint8'>
72 <class 'numpy.uint8'>


In [67]:
img.shape[0]*img.shape[1]*img.shape[2]

1075200

In [77]:
config_arr = RawArray('c', (5, 8))

In [78]:
print(config_arr[1], type(config_arr[0]))

b'\x08' <class 'bytes'>
